apiVersion: apps/v1
kind: Deployment
metadata:
  name: bespokedbikesfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bespokedbikesfrontend
  template:
    metadata:
      labels:
        app: bespokedbikesfrontend
    spec:
      containers:
      - name: bespokedbikesfrontend
        image: bespokedbikes.azurecr.io/kassiburnett/bespokedbikesfrontend:latest
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bespokedbikesfrontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: bespokedbikesfrontend